### ISSUE TITLE
When granted to and granted on have the same name but different types, only one node is visible.

### ISSUE THREAD

**Issue by ganeshx** [hashmapinc/snowflake-inspector#58]
<img width="463" alt="Screen Shot 2020-06-09 at 2 32 20 PM (1)" src="https://user-images.githubusercontent.com/644158/84213729-105c1b00-aa87-11ea-9f58-615f730b0a9e.png">

**Comment by randypitcherii** [comment]
Potentially consider adding the object type to the end of the object name to identify correctly
